# This dockerfile builds an openssh server that will accept any SSH keys signed by the key provided in /mnt/keybase-ca-key.pub
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Set up the SSH server to trust the CA key for all users
RUN echo "TrustedUserCAKeys /etc/ssh/ca.pub" >> /etc/ssh/sshd_config

# Used in the integration tests by reading the contents of this file. See test_kssh.py
RUN echo -n "uniquestring" > /etc/unique

EXPOSE 22

CMD while ! [ -f /mnt/keybase-ca-key.pub ]; do sleep 1; done && echo " Starting sshd..." && ln -sf /mnt/keybase-ca-key.pub /etc/ssh/ca.pub && /usr/sbin/sshd -D
