# This dockerfile builds a container capable of running kssh. Note that a lot of this code is duplicated
# between this file and Dockerfile-ca.
FROM ubuntu:18.04

# Dependencies
RUN apt-get -qq update
RUN apt-get -qq  install curl software-properties-common ca-certificates gnupg -y
RUN useradd -ms /bin/bash keybase
USER keybase
WORKDIR /home/keybase

# Download and verify the deb
RUN curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
RUN curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb.sig
# GPG has no easy way of getting the ID associated with a key, so we do this :(
# This line will error if the fingerprint of the key in the file does not match
# Key fingerprint from https://keybase.io/docs/server_security/our_code_signing_key
# Note that we do it this way rather than via the key servers since pulling from the
# key servers caused a flakey build
RUN gpg --with-colons --fingerprint $( \
        curl -sSL https://keybase.io/docs/server_security/code_signing_key.asc | \
        gpg --import 2>&1 | \
        grep -v created | \
        head -n 1 | \
        cut -d ' ' -f 3 | \
        cut -d ':' -f 1 \
    ) | grep fpr | cut -d ':' -f 10 | grep 222B85B0F90BE2D24CFEB93F47484E50656D16C7
RUN gpg --verify keybase_amd64.deb.sig keybase_amd64.deb

# Silence the error from dpkg about failing to configure keybase since `apt-get install -f` fixes it
USER root
RUN dpkg -i keybase_amd64.deb || true
RUN apt-get install -fy
USER keybase

# Install go
USER root
RUN add-apt-repository ppa:gophers/archive -y
RUN apt-get update -y
RUN apt-get install golang-1.11-go git sudo python3 python3-pip sudo -y
RUN pip3 install pytest requests

# Make it so the keybase user has passwordless sudo so it can move the keybase binary around
RUN echo "keybase ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/keybase && \
    chmod 0440 /etc/sudoers.d/keybase

# Install go dependencies (speeds up future builds)
COPY --chown=keybase go.mod .
COPY --chown=keybase go.sum .
RUN /usr/lib/go-1.11/bin/go mod download

COPY --chown=keybase ./ /home/keybase/
RUN /usr/lib/go-1.11/bin/go build -o bin/kssh src/cmd/kssh/kssh.go

USER root