# This dockerfile builds an openssh server that will accept SSH keys signed by the key provided in /mnt/keybase-ca-key.pub
# It takes in a build argument and only allows keys with the build argument in the principals field
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openssh-server inotify-tools
RUN mkdir /var/run/sshd

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

ARG allowed_principal
RUN mkdir /etc/ssh/auth_principals/
RUN useradd -ms /bin/bash user
RUN mkdir /root/.ssh/
RUN mkdir /home/user/.ssh/

# Used in the integration tests by reading the contents of this file. See test_kssh.py
RUN echo -n "uniquestring" > /etc/unique

EXPOSE 22

CMD touch /mnt/keybase-ca-key.pub && (while inotifywait -e close_write /mnt/keybase-ca-key.pub; do echo "cert-authority,principals=\"$root_everywhere_principal\" `cat /mnt/keybase-ca-key.pub`" > /root/.ssh/authorized_keys; echo "cert-authority,principals=\"$allowed_principal\" `cat /mnt/keybase-ca-key.pub`" > /home/user/.ssh/authorized_keys; done) & /usr/sbin/sshd -D