# See docker/Dockerfile-keybase
FROM keybase:latest

# Install go
USER root
RUN add-apt-repository ppa:gophers/archive -y
RUN apt-get update && apt-get install golang-1.11-go git sudo -y
USER keybase

# Install go dependencies (speeds up future builds)
COPY --chown=keybase go.mod .
COPY --chown=keybase go.sum .
RUN /usr/lib/go-1.11/bin/go mod download

COPY --chown=keybase ./ /home/keybase/

RUN /usr/lib/go-1.11/bin/go build -o bin/keybaseca src/cmd/keybaseca/keybaseca.go

USER root